version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run: node -v
      - run: npm run eslint -v
      - run: eslint -v
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
            
      
